### ISSUE TITLE
Makefile doesn't build

### ISSUE THREAD

**Issue by hyiltiz** [komar007/multixonix#1]
Trying to make this https://github.com/komar007/multixonix/blob/master/Makefile, but kept getting `Makefile.dep:1: *** missing separator.  Stop.`
Checked with emacs for visible whitepsaces; they all seem correct (tabs used properly) in the Makefile.
Checked for the line endings, ASCII encoding etc.
Any idea what's preventing it?

None of the answers here helped https://stackoverflow.com/questions/18936337/makefile1-missing-separator-stop

**Comment by komar007** [comment]
@hyiltiz 
This is some very old code I wrote while on studies. It was never finished, it is likely buggy, and all I remember from it is that I didn't know C++, overdesigned everything about it and dropped development at a very early stage.
Feel free to use parts of it, but please don't waste your time trying to build it, because it's less than a simple computational geometry demo without real value.

As for the Makefile, its recipe generation is not needed, `-M` should give correct dependency output and those recipes should be in the Makefile and generic. Likely something is wrongly or unportably generated there.

**Comment by hyiltiz** [comment]
Thx for letting me know a little more about the history of the project. I was just compiling (a list of) all implementations of xonix in github, and some of them needed compilation (as yours). Wasted about a week trying to compile it, and every time I fixed something, something else seemed broken. I just assumed it was a working code back then, so tried to go back in time with the dependencies etc. Anyway, I'll get on with life and forget about it for now.
